
module.exports = { // first five parameters are for PostgreSQL connection...
    HOST: "localhost",
    USER: "postgres",
    PASSWORD: "password", //here change by a real password...
    DB: "tutoriales",
    dialect: "postgres",
    pool: {
      max: 5, //maximum number of connection in pool...
      min: 0, //minimum number of connection in pool...
      acquire: 30000, //maximum time, in milliseconds, that pool will try to get connection before throwing error...
      idle: 10000 // maximum time, in miliseconds, that a connection can be idle before being released...
    }
};